I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    image sl_idle scale = im.Scale(sl_idle, 400, 200)
  File "game/script.rpy", line 9, in <module>
    image sl_idle scale = im.Scale(sl_idle, 400, 200)
NameError: name 'sl_idle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    image sl_idle scale = im.Scale(sl_idle, 400, 200)
  File "C:\Users\Tom\Documents\renpy-6.99.5-sdk\renpy\ast.py", line 888, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Tom\Documents\renpy-6.99.5-sdk\renpy\python.py", line 1472, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 9, in <module>
    image sl_idle scale = im.Scale(sl_idle, 400, 200)
NameError: name 'sl_idle' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.5.602
Hardwired 0.0
